# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestALUNOvalidaocamposobrigatrios():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_aLUNOvalidaocamposobrigatrios(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1536, 816)
    self.driver.find_element(By.LINK_TEXT, "Gerenciar Alunos").click()
    self.driver.find_element(By.ID, "id-nome_completo").click()
    self.driver.find_element(By.ID, "id-nome_completo").send_keys("João da Silva")
    self.driver.find_element(By.ID, "id-cpf").click()
    self.driver.find_element(By.ID, "id-cpf").send_keys("111.222.333-44")
    self.driver.find_element(By.ID, "id-data_nascimento").click()
    self.driver.find_element(By.ID, "id-data_nascimento").send_keys("0002-10-04")
    self.driver.find_element(By.ID, "id-data_nascimento").send_keys("0020-10-04")
    self.driver.find_element(By.ID, "id-data_nascimento").send_keys("0200-10-04")
    self.driver.find_element(By.ID, "id-data_nascimento").send_keys("2006-10-04")
    self.driver.find_element(By.ID, "id-email").click()
    self.driver.find_element(By.ID, "id-email").send_keys("joao@gmail.com")
    self.driver.find_element(By.ID, "id-telefone").click()
    self.driver.find_element(By.ID, "id-endereco").click()
    self.driver.find_element(By.ID, "id-endereco").send_keys("Rua Agonia, 123")
    self.driver.find_element(By.ID, "id-botao-salvar").click()
    self.driver.find_element(By.NAME, "search_nome").click()
  
