# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMATRICULAvalidaoduplicidadedematricula():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_mATRICULAvalidaoduplicidadedematricula(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1534, 814)
    self.driver.find_element(By.LINK_TEXT, "Gerenciar Matrículas").click()
    self.driver.find_element(By.ID, "id-aluno_id").click()
    dropdown = self.driver.find_element(By.ID, "id-aluno_id")
    dropdown.find_element(By.XPATH, "//option[. = 'Ana da Silva (111.111.111-11)']").click()
    self.driver.find_element(By.ID, "id-plano_id").click()
    dropdown = self.driver.find_element(By.ID, "id-plano_id")
    dropdown.find_element(By.XPATH, "//option[. = 'Plano Anual']").click()
    self.driver.find_element(By.ID, "id-data_inicio").click()
    self.driver.find_element(By.ID, "id-data_inicio").send_keys("0002-01-15")
    self.driver.find_element(By.ID, "id-data_inicio").send_keys("0020-01-15")
    self.driver.find_element(By.ID, "id-data_inicio").send_keys("0202-01-15")
    self.driver.find_element(By.ID, "id-data_inicio").send_keys("2023-01-15")
    self.driver.find_element(By.ID, "id-botao-salvar").click()
    self.driver.find_element(By.ID, "id-aluno_id").click()
    self.driver.find_element(By.ID, "id-plano_id").click()
  
