# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFUNCIONARIOvalidaoedio():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_fUNCIONARIOvalidaoedio(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1534, 814)
    self.driver.find_element(By.LINK_TEXT, "Gerenciar Funcionários").click()
    self.driver.find_element(By.ID, "id-btn-editar-1").click()
    self.driver.find_element(By.ID, "id-salario").click()
    self.driver.find_element(By.ID, "id-salario").send_keys("4000.00")
    self.driver.find_element(By.ID, "id-contato").click()
    self.driver.find_element(By.ID, "id-botao-salvar-edicao").click()
    self.driver.find_element(By.ID, "id-nome").click()
  
