# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCRUDPLANOS():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cRUDPLANOS(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1456, 868)
    self.driver.find_element(By.LINK_TEXT, "Gerenciar Alunos").click()
    self.driver.find_element(By.LINK_TEXT, "Gerenciar Planos").click()
    self.driver.find_element(By.ID, "id-nome_plano").click()
    self.driver.find_element(By.ID, "id-nome_plano").send_keys("Plano Mensal")
    self.driver.find_element(By.ID, "id-descricao").click()
    self.driver.find_element(By.ID, "id-descricao").send_keys("Acesso todas as areas")
    self.driver.find_element(By.ID, "id-valor_mensal").click()
    self.driver.find_element(By.ID, "id-valor_mensal").send_keys("99.99")
    self.driver.find_element(By.ID, "id-duracao_meses").click()
    self.driver.find_element(By.ID, "id-duracao_meses").send_keys("12")
    self.driver.find_element(By.ID, "id-botao-salvar").click()
    self.driver.find_element(By.ID, "id-nome_plano").click()
    self.driver.find_element(By.ID, "id-nome_plano").send_keys("Plano Mensal")
    self.driver.find_element(By.ID, "id-nome_plano").send_keys("Plano Semestral")
    self.driver.find_element(By.ID, "id-descricao").click()
    self.driver.find_element(By.ID, "id-descricao").send_keys("Acesso todas as areas")
    self.driver.find_element(By.ID, "id-descricao").click()
    self.driver.find_element(By.ID, "id-descricao").click()
    self.driver.find_element(By.ID, "id-descricao").send_keys("Acesso a algumas áreas")
    self.driver.find_element(By.ID, "id-valor_mensal").click()
    self.driver.find_element(By.ID, "id-valor_mensal").send_keys("49.99")
    self.driver.find_element(By.ID, "id-duracao_meses").click()
    self.driver.find_element(By.ID, "id-duracao_meses").send_keys("6")
    self.driver.find_element(By.ID, "id-status").click()
    dropdown = self.driver.find_element(By.ID, "id-status")
    dropdown.find_element(By.XPATH, "//option[. = 'Inativo']").click()
    self.driver.find_element(By.ID, "id-botao-salvar").click()
    self.driver.find_element(By.NAME, "search_status").click()
    dropdown = self.driver.find_element(By.NAME, "search_status")
    dropdown.find_element(By.XPATH, "//option[. = 'Ativo']").click()
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(3)").click()
    self.driver.find_element(By.NAME, "search_nome_plano").click()
    self.driver.find_element(By.NAME, "search_status").click()
    dropdown = self.driver.find_element(By.NAME, "search_status")
    dropdown.find_element(By.XPATH, "//option[. = 'Todos os Status']").click()
    self.driver.find_element(By.NAME, "search_nome_plano").click()
    self.driver.find_element(By.NAME, "search_nome_plano").send_keys("Plano mensal")
    self.driver.find_element(By.NAME, "search_nome_plano").send_keys("Plano semestral")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(3)").click()
    self.driver.find_element(By.ID, "id-btn-editar-3").click()
    self.driver.find_element(By.ID, "id-status").click()
    self.driver.find_element(By.ID, "id-status").click()
    self.driver.find_element(By.ID, "id-valor_mensal").click()
    self.driver.find_element(By.ID, "id-valor_mensal").send_keys("80.00")
    self.driver.find_element(By.ID, "id-botao-salvar-edicao").click()
    self.driver.find_element(By.ID, "id-btn-remover-2").click()
    self.driver.find_element(By.ID, "id-btn-remover-3").click()
  
