# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMANUTENOAlterastatusaparelho():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_mANUTENOAlterastatusaparelho(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.find_element(By.LINK_TEXT, "Gerenciar Aparelhos").click()
    self.driver.find_element(By.LINK_TEXT, "Gerenciar Manutenções").click()
    self.driver.find_element(By.ID, "id-btn-editar-6").click()
    self.driver.find_element(By.ID, "id-data_conclusao").click()
    self.driver.find_element(By.ID, "id-data_conclusao").send_keys("0002-10-05")
    self.driver.find_element(By.ID, "id-data_conclusao").send_keys("0020-10-05")
    self.driver.find_element(By.ID, "id-data_conclusao").send_keys("0202-10-05")
    self.driver.find_element(By.ID, "id-data_conclusao").send_keys("2025-10-05")
    self.driver.find_element(By.ID, "id-botao-salvar-edicao").click()
    self.driver.find_element(By.LINK_TEXT, "Gerenciar Aparelhos").click()
    self.driver.find_element(By.CSS_SELECTOR, ".container").click()
  
