# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFUNCIONARIOvalidaocriao():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_fUNCIONARIOvalidaocriao(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1536, 816)
    self.driver.find_element(By.LINK_TEXT, "Gerenciar Funcionários").click()
    self.driver.find_element(By.ID, "id-nome").click()
    self.driver.find_element(By.ID, "id-nome").send_keys("Pedro")
    self.driver.find_element(By.ID, "id-cpf").click()
    self.driver.find_element(By.ID, "id-cpf").send_keys("111.222.333-44")
    self.driver.find_element(By.ID, "id-cargo").click()
    dropdown = self.driver.find_element(By.ID, "id-cargo")
    dropdown.find_element(By.XPATH, "//option[. = 'Instrutor']").click()
    self.driver.find_element(By.ID, "id-data_admissao").click()
    self.driver.find_element(By.ID, "id-data_admissao").send_keys("0002-10-04")
    self.driver.find_element(By.ID, "id-data_admissao").send_keys("0020-10-04")
    self.driver.find_element(By.ID, "id-data_admissao").send_keys("0200-10-04")
    self.driver.find_element(By.ID, "id-data_admissao").send_keys("2006-10-04")
    self.driver.find_element(By.ID, "id-salario").click()
    self.driver.find_element(By.ID, "id-salario").send_keys("1800.00")
    self.driver.find_element(By.ID, "id-contato").click()
    self.driver.find_element(By.ID, "id-contato").send_keys("(35) 99999999")
    self.driver.find_element(By.ID, "id-botao-salvar").click()
    self.driver.find_element(By.NAME, "search_nome").click()
  
