# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMANUTENOvalidaodemanutenoalteraodestatus():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_mANUTENOvalidaodemanutenoalteraodestatus(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.find_element(By.LINK_TEXT, "Gerenciar Aparelhos").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > td:nth-child(3)").click()
    self.driver.find_element(By.LINK_TEXT, "Gerenciar Manutenções").click()
    self.driver.find_element(By.ID, "id-aparelho_id").click()
    dropdown = self.driver.find_element(By.ID, "id-aparelho_id")
    dropdown.find_element(By.XPATH, "//option[. = 'Halteres Ajustáveis']").click()
    self.driver.find_element(By.ID, "id-funcionario_id").click()
    dropdown = self.driver.find_element(By.ID, "id-funcionario_id")
    dropdown.find_element(By.XPATH, "//option[. = 'Elias Técnico']").click()
    self.driver.find_element(By.ID, "id-data_inicio").click()
    self.driver.find_element(By.ID, "id-data_inicio").send_keys("0002-10-04")
    self.driver.find_element(By.ID, "id-data_inicio").send_keys("0020-10-04")
    self.driver.find_element(By.ID, "id-data_inicio").send_keys("0202-10-04")
    self.driver.find_element(By.ID, "id-data_inicio").send_keys("2025-10-04")
    self.driver.find_element(By.ID, "id-descricao_problema").click()
    self.driver.find_element(By.ID, "id-descricao_problema").send_keys("Ruído")
    self.driver.find_element(By.ID, "id-custo").click()
    self.driver.find_element(By.ID, "id-custo").send_keys("50.00")
    self.driver.find_element(By.ID, "id-botao-salvar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".container").click()
    self.driver.find_element(By.LINK_TEXT, "Gerenciar Aparelhos").click()
    self.driver.find_element(By.CSS_SELECTOR, ".main-content").click()
  
