# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestALUNOvalidaoconsultaporCPF():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_aLUNOvalidaoconsultaporCPF(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1536, 816)
    self.driver.find_element(By.LINK_TEXT, "Gerenciar Alunos").click()
    self.driver.find_element(By.NAME, "search_cpf").click()
    self.driver.find_element(By.NAME, "search_cpf").send_keys("111.111.111-11")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-filtro").click()
    self.driver.find_element(By.NAME, "search_cpf").send_keys("222.222.222-22")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(3)").click()
  
