# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPLANOvalidaodeduplicidadedeplano():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pLANOvalidaodeduplicidadedeplano(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1536, 816)
    self.driver.find_element(By.LINK_TEXT, "Gerenciar Planos").click()
    self.driver.find_element(By.ID, "id-nome_plano").click()
    self.driver.find_element(By.ID, "id-nome_plano").send_keys("Plano Mensal")
    self.driver.find_element(By.ID, "id-duracao_meses").click()
    self.driver.find_element(By.ID, "id-duracao_meses").send_keys("12")
    self.driver.find_element(By.ID, "id-descricao").click()
    self.driver.find_element(By.ID, "id-descricao").send_keys("Acesso a algumas áreas")
    self.driver.find_element(By.ID, "id-valor_mensal").click()
    self.driver.find_element(By.ID, "id-valor_mensal").send_keys("99.99")
    self.driver.find_element(By.ID, "id-botao-salvar").click()
    self.driver.find_element(By.NAME, "search_nome_plano").click()
  
